# Generated by Django 6.0.6 on 2026-06-06 05:50

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique secure identifier. Uses random UUID4 to prevent guessing account URLs.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The legal or display name of the account holder (e.g., 'Sachin Venkatesh').", max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current available funds. Decimal type is strictly used to eliminate floating-point rounding errors.', max_digits=12)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
