# Generated by Django 6.0.6 on 2026-06-24 13:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
